# Context-MCP Observability Stack
# OpenTelemetry Collector + Jaeger + Prometheus + Grafana
#
# Usage:
#   docker-compose -f docs/observability-stack.yml up -d    # Start monitoring stack
#   docker-compose -f docs/observability-stack.yml down     # Stop monitoring stack
#   docker-compose -f docs/observability-stack.yml logs     # View logs
#
# Services:
#   - Jaeger: http://localhost:16686 (Trace UI)
#   - Prometheus: http://localhost:9090 (Metrics)
#   - Grafana: http://localhost:3000 (Dashboard, admin/admin)
#   - OTLP Collector: http://localhost:4317 (OTLP gRPC)

services:
  # OpenTelemetry Collector
  # Receives OTLP data and exports to Jaeger/Prometheus
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.115.1
    container_name: context-mcp-otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # Health check extension
    networks:
      - observability

  # Jaeger
  # Distributed tracing backend and UI
  jaeger:
    image: jaegertracing/all-in-one:1.65.0
    container_name: context-mcp-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # Jaeger gRPC
      - "14268:14268"  # Jaeger HTTP
    networks:
      - observability

  # Prometheus
  # Metrics storage and query engine
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: context-mcp-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./prometheus-sample.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - observability

  # Grafana
  # Visualization and dashboarding
  grafana:
    image: grafana/grafana:11.4.0
    container_name: context-mcp-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    networks:
      - observability
    depends_on:
      - prometheus
      - jaeger

volumes:
  prometheus-data:
  grafana-data:

networks:
  observability:
    driver: bridge
